orbs:
  docker: circleci/docker@1.5.0
version: 2.1
executors:
  docker-publisher: 
    environment:
      - IMAGE_NAME: mahamarif/sentiment-analysis-s140-lstm
        GIT_LFS_SKIP_SMUDGE: 1
    docker: # Each job requires specifying an executor
    # (either docker, macos, or machine), see
      - image: circleci/node:latest
        auth:
            username: $DOCKERHUB_USERNAME
            password: $DOCKERHUB_PASSWORD

jobs:
    publishLatestToHub: 
      executor: docker-publisher
 
      steps: 
        - checkout
        - run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id
        - restore_cache:
          keys:
            - v1-lfscache-{{ checksum ".lfs-assets-id" }}
            - v1-lfscache-
        - run: git lfs pull
        - save_cache:
          paths:
            - .git/lfs
          key: v1-lfscache-{{ checksum ".lfs-assets-id" }}
        - setup_remote_docker
        - run: 
            name: Publish Docker Image to Docker Hub
            command: |
              echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
              docker build -t $IMAGE_NAME .
              docker push $IMAGE_NAME:latest

workflows:
  version: 2
  build-master:
    jobs:
       - publishLatestToHub
          
                
                 
             
    
       
      


    
           
   
    

    
